export const buttons = [
    { value: '+', type: 'operator', format: 'double' },
    { value: '-', type: 'operator', format: 'double' },
    { value: '1', type: 'number', format: 'simple' },
    { value: '2', type: 'number', format: 'simple' },
    { value: '3', type: 'number', format: 'simple' },
    { value: '4', type: 'number', format: 'simple' },
    { value: '5', type: 'number', format: 'simple' },
    { value: '6', type: 'number', format: 'simple' },
    { value: '7', type: 'number', format: 'simple' },
    { value: '8', type: 'number', format: 'simple' },
    { value: '9', type: 'number', format: 'simple' },
    { value: '0', type: 'number', format: 'simple' },
    { value: 'C', type: 'operator', format: 'double' },
    { value: '=', type: 'operator', format: 'enter' },
];
